name: Deploy into production server

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy at remote server
        uses: appleboy/ssh-action@master
        with:
          remote_path: 
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_KEY }}
          port:     ${{ secrets.SSH_PORT }}
          envs: DIR
          script_stop: true
          script: |
            source .bashrc
            cd $DIR
            
            if [ -d conoha-test ]; then
              cd conoha-test
            fi
            pwd

            # Check if .git directory exists
            if [ ! -d .git ]; then
              git clone https://github.com/shingo119/conoha-test.git
            fi

            git pull origin main

            # Check if composer.phar exists, if not download and install it
            if [ ! -f composer.phar ]; then
                curl -sS https://getcomposer.org/installer | php
            fi

            composer.phar install
            php artisan migrate
            php artisan db:seed
        env:
          DIR: public_html/yubase-conoha-test.com