name: Deploy into production server

# on:
#   pull_request:
#     types:
#       - closed
#     branches:
#       - main

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: deploy at remote server
        uses: appleboy/ssh-action@master
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_KEY }}
          port:     ${{ secrets.SSH_PORT }}
          envs: PROJECT_DIR
          script_stop: true
          script: |
            source .bashrc
            cd $PROJECT_DIR

            if [ ! -d ".git" ]; then
              git clone https://github.com/shingo119/conoha-test.git .
              echo "git clone"
            fi

            if [ -d ".git" ]; then
              git pull
              echo "git pull origin main"
            fi

            php composer install

            # php artisan config:cache
            # php artisan route:cache
            # php artisan view:cache

            # php artisan migrate --force
            # php artisan db:seed --force

            npm i && npm run build
            
        env:
          PROJECT_DIR: "public_html/yubase-conoha-test.com"