name: Deploy into production server

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: deploy at remote server
        uses: appleboy/ssh-action@master
        with:
          remote_path: 
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_KEY }}
          port:     ${{ secrets.SSH_PORT }}
          envs: DIR
          script_stop: true
          script: |
            source .bashrc
            # cd $DIR
            pwd
            echo $DIR
            echo "$DIR"

            if [ ! -d $DIR ]; then
              # git clone https://github.com/shingo119/conoha-test.git $DIR
              echo "not exist"
            fi

            if [ ! -d "$DIR" ]; then
              # git clone https://github.com/shingo119/conoha-test.git $DIR
              echo "not exist2"
              mkdir "$DIR"
            fi

            if [ -d $DIR ]; then
              echo "exist"
            fi

            if [ -d "$DIR" ]; then
              echo "exist2"
            fi

            # git clone https://github.com/shingo119/conoha-test.git

            # cd $DIR

            # composerがインストールされていなければインストールする
            # if [ ! -f composer.phar ]; then
            #     curl -sS https://getcomposer.org/installer | php
            # fi

            # php composer.phar install
            # mysql.server start
            # php artisan migrate --force
            # php artisan db:seed --force

            # git pull origin main

            

            # php composer.phar install
            # mysql.server start
            # php artisan migrate --force
            # php artisan db:seed --force
        env:
          DIR: "conoha-test"