name: Deploy into production server

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy at remote server
        uses: appleboy/ssh-action@master
        with:
          remote_path: 
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_KEY }}
          port:     ${{ secrets.SSH_PORT }}
          envs: DIR
          script_stop: true
          script: |
            source .bashrc
            cd $DIR

            # Check if .git directory exists
            if [ ! -d ".git" ]; then
              git clone https://github.com/shingo119/conoha-test.git .
            else
            git pull origin main -f
            fi

            php composer install
            php artisan migrate
            php artisan db:seed --force
        env:
          DIR: public_html/yubase-conoha-test.com